<?php

// project globals
const D9M7_PROJECT_NAME = 'Drift Eleven';
const D9M7_PROJECT_ID = 'drift_eleven';

// directory discovery
const D9M7_CORE_ROUTES_DIR = __DIR__ . '\src\Core\Routes';

// configuration
const D9M7_CONFIG_KEY = 'drift_eleven.settings';
const D9M7_LOGGER_KEY = 'drift_eleven.logger';
const D9M7_CACHE_KEY = 'drift_eleven.cache';
const D9M7_CACHE_BIN_KEY = 'drift_eleven';


// v2
const LOGGER_DEBUG = true;

const CACHE_BIN_KEY_DEFAULT = 'de_bin';
const CACHE_TAGS_BIN_KEY_DEFAULT = 'de_tags_bin';
const CACHE_DURATION_DEFAULT = 3600;
